dependencies:
  - conda-forge::pip=21.0.1
  - conda-forge::python=3.10
  - pip:
      - matplotlib
      - numpy==1.26.3
      - seaborn
      - git+https://github.com/lamalab-org/chem-bench.git@humanbench