dependencies:
  - conda-forge::pip=23.3.1
  - conda-forge::python=3.10
  - pymatgen
  - pip:
      - torch==2.2.0
      - transformers==4.37.2
      - accelerate==0.26.1
      - matplotlib
      - pulp==2.7.0
      - numpy==1.26.3
      - seaborn
      - textacy==0.13.0
      - wordcloud
      - rdkit
      - git+https://github.com/lamalab-org/chem-bench.git
